name: testbintoro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  # flutter_local_notifications: ^11.0.0
  flutter_local_notifications: ^9.1.5
  get: 4.6.5
  flutter:
    sdk: flutter
  timezone: ^0.8.0
  flutter_form_builder: ^7.6.0
  form_builder_validators: ^8.3.0
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  timeago: ^3.3.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9
  flutter_test:
    sdk: flutter


#flutter pub run flutter_native_splash:create
flutter_native_splash: 
  image: "assets/icons/logo_test.png"
  color: "#52B3D9"


#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/logo_test.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
